### ISSUE TITLE
Images are not working in Technology Stacks .

### ISSUE THREAD

**Issue by Kushal997-das** [HarshCasper/harshcasper#8]
<img width="700" alt="harsh (2)" src="https://user-images.githubusercontent.com/61356005/104902638-fb445480-59a4-11eb-8dd6-b2e56733eccf.PNG">

**Comment by HarshCasper** [comment]
Yes, they are not working. I would look to fix it soon but is definitely not on the priority for now. 

It would be great if you can raise a PR for the same.

**Comment by Kushal997-das** [comment]
Gonna fix this issue and send you PR :)
